# Generated by Django 3.2.2 on 2021-05-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_img_confession_conf_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='conf_img',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
