# Generated by Django 3.2.2 on 2021-05-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_confession_conf_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='conf_img',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
